
const dict = {
        'ru': {
            'change_qs_1_btn': 'На модерацию',
            'change_qs_2_btn': 'Опубликовать',
            'change_qs_3_btn': 'Отклонить',
            'tests_lbl': 'Тесты',
            'logout': 'выйти',
            'users_mi': 'Пользователи',
            'kb_mi': 'База Знаний',
            'tests_mi': 'Тесты',
            'contacts_mi': 'Контакты',
            'close_btn': 'закрыть',
            'text_lbl': 'Текст',
            'file_lbl': 'Файл',
            'answers_text_h': 'текст',
            'answers_correct_h': 'правильный',
            'add_answer_btn': 'Добавить ответ',
            'categories_h': 'Категории',
            'category_h': 'Категория',
            'save': 'сохранить',
            'add_category': 'Добавить категорию',
            'edit': 'Редактировать',
            'delete': 'Удалить',
            'name_lbl': 'Название',
            'hname_lbl': 'Имя',
            'contacts_h': 'Контакты',
            'kb_h': 'База знаний',
            'url_lbl': 'URL',
            'lessons_h': 'Лекции',
            'login_lbl': 'Логин',
            'password_lbl': 'Пароль',
            'correct_answer_lbl': 'Правильный ответ',
            'phases_h': 'Стадии',
            'add_phase_btn': 'Добавить стадию',
            'questions_h': 'Вопросы',
            'add_question_btn': 'Добавить вопрос',
            'woa': 'с открытым ответом',
            'wal': 'со списком ответов',
            'tests_h': 'Тесты',
            'add_test_btn': 'Добавить тест',
            'option_all': 'Все',
            'option_0': 'В процессе',
            'option_1': 'На модерации',
            'option_2': 'Опубликованные',
            'option_3': 'Отклонённые',
            'users_h': 'Пользователи',
            'question_h': 'Вопросы',
            'lesson_h': 'Лекция',
            'level_h': 'Уровень',
            'phase_h': 'Стадия',
            'user_h': 'Пользователь',
            'yes_option': 'да',
            'no_option': 'нет',
            'test_h': 'Тест',
            'questions_lbl': 'вопросы',
            'answers_actions_h': 'действия',
            'add_level_btn': 'Добавить уровень',
            'phases_lbl': 'Этапы',
            'lessons_lbl': 'Лекции',
            'add_lesson_btn': 'Добавить лекцию',
            'dontchangepassword': 'Не менять пароль',
            'add_user_btn': 'Добавить пользователя',
            'login_h': 'Вход',
            'login_btn': 'Войти',
            'saved_ntf': 'Сохранено',
            'deleted_ntf': 'Удалено',
            'error_ntf': 'Ошибка',
            'changed_ntf': 'Изменено',
            'enter_name': 'Введите название',
            'enter_hname': 'Введите имя',
            'enter_text': 'Введите текст',
            'enter_login': 'Введите логин',
            'enter_password': 'Введите пароль',
            'enter_question_text': 'Введите текст вопроса',
            'enter_url': 'Введите url',
            'enter_correct_answer': 'Введите правильный ответ',
            'duplicated_name': 'Повторяющееся название',
            'duplicated_login': 'Повторяющийся логин',
            'duplicated_text': 'Повторяющаяся формулировка',
            'add_answer': 'Добавьте ответ',
            'incorrect_password': 'Неверный пароль',
            'detach_file': 'Удалить файл',
            'not_found_h': 'Не найдено',
            'not_found_t': 'Запрошенная страница не найдена',
            'save_order':'Сохранить порядок',
            'change_order': 'Изменить порядок',
            'visible_lbl': 'Видимая'
        },
        'en': {
            'change_qs_1_btn': 'for moderation',
            'change_qs_2_btn': 'publish',
            'change_qs_3_btn': 'reject',
            'questions_lbl': 'questions',
            'tests_lbl': 'tests',
            'logout': 'log out',
            'users_mi': 'Users',
            'kb_mi': 'Knowledge Base',
            'tests_mi': 'Tests',
            'test_h': 'Test',
            'contacts_mi': 'Contacts',
            'close_btn': 'close',
            'text_lbl': 'Text',
            'file_lbl': 'File',
            'answers_text_h': 'text',
            'answers_correct_h': 'correct',
            'answers_actions_h': 'actions',
            'add_answer_btn': 'Add answer',
            'categories_h': 'Categories',
            'category_h': 'Category',
            'save': 'Save',
            'add_category': 'Add category',
            'edit': 'edit',
            'delete': 'delete',
            'name_lbl': 'Name',
            'hname_lbl': 'Name',
            'contacts_h': 'Contacts',
            'kb_h': 'Knowledge Base',
            'url_lbl': 'URL',
            'lessons_h': 'Lessons',
            'login_lbl': 'login',
            'password_lbl': 'password',
            'correct_answer_lbl': 'Correct answer',
            'phases_h': 'phases',
            'add_phase_btn': 'Add phases',
            'questions_h': 'Questions',
            'add_question_btn': 'Add questions ',
            'woa': 'with open answer',
            'wal': 'With answers list',
            'tests_h': 'Tests',
            'add_test_btn': 'Add test',
            'option_all': 'All',
            'option_0': 'In process',
            'option_1': 'Moderating',
            'option_2': 'Published',
            'option_3': 'Rejected',
            'users_h': 'Users',
            'question_h': 'Question',
            'lesson_h': 'Lesson',
            'level_h': 'Level',
            'phase_h': 'Phase',
            'user_h': 'User',
            'yes_option': 'yes',
            'no_option': 'no',
            'add_level_btn': 'Add level',
            'phases_lbl': 'phases',
            'lessons_lbl': 'lessons',
            'add_lesson_btn': 'Add lesson',
            'dontchangepassword': 'Don\'t change password',
            'add_user_btn': 'Add user',
            'login_h': 'Log in',
            'login_btn': 'Log in',
            'saved_ntf': 'Saved',
            'changed_ntf': 'Changed',
            'deleted_ntf': 'Deleted',
            'error_ntf': 'Error',
            'enter_name': 'Enter name',
            'enter_hname': 'Enter name',
            'enter_login': 'Enter login',
            'enter_text': 'Enter text',
            'enter_password': 'Enter password',
            'enter_question_text': 'Enter question text',
            'enter_url': 'Enter url',
            'enter_correct_answer': 'Enter correct answer',
            'duplicated_name': 'Duplicated name',
            'duplicated_login': 'Duplicated login',
            'duplicated_text': 'Duplicated text',
            'add_answer': 'Add answer',
            'incorrect_password': 'Incorrect password',
            'detach_file': 'Delete file',
            'not_found_h': 'Not Found',
            'not_found_t': 'Page not found',
            'save_order':'Save order',
            'change_order': 'Change order',
            'visible_lbl': 'Visible'
        }
    };


export {dict};